// Legal pages (privacy policy, terms of use).
// Minimal rich markup: <b>…</b> (bold) and <i>…</i> (italic), rendered by the component.
export const legal = {
  common: {
    backHome: '← Back to home',
    companyAddress: 'Registered office address — to be completed',
  },
  privacy: {
    metaTitle: 'Privacy Policy — Medjira',
    metaDescription:
      'Privacy Policy of the Medjira app (taxi, food and parcel delivery). GDPR and Google Play compliant.',
    title: 'Privacy Policy',
    lastUpdated: 'Last updated: {date}',
    updatedDate: 'May 2, 2026',
    intro1:
      'This policy describes how <b>{company}</b> ("we", "our", "Medjira") collects, uses, shares and protects the personal data of users of the Medjira mobile application and website (the "Services").',
    intro2:
      'By using the Services, you accept the practices described below. This policy complies with the <b>General Data Protection Regulation (GDPR — EU 2016/679)</b>, the <b>French Data Protection Act (Loi Informatique et Libertés)</b> and the requirements of <b>Google Play Data Safety</b>.',
    s1: {
      title: '1. Data controller',
      websiteLabel: 'Website:',
      contactLabel: 'Data protection contact:',
    },
    s2: {
      title: '2. Data we collect',
      directTitle: '2.1 Data you provide directly',
      direct: {
        identity: '<b>Identity</b>: last name, first name, date of birth.',
        contact:
          '<b>Contact details</b>: email address, phone number, postal address (deliveries).',
        credentials:
          '<b>Login credentials</b>: Firebase authentication (email / Google / Apple) and phone verification by SMS.',
        photo:
          '<b>Profile photo</b> and, for drivers, identity documents, driving licence, vehicle registration certificate, insurance certificate (regulatory verification).',
        payment:
          '<b>Payment data</b>: processed exclusively by our provider <b>Stripe</b> (PCI-DSS Level 1 standard). We never store your card numbers.',
      },
      autoTitle: '2.2 Data collected automatically',
      auto: {
        gps: '<b>Precise location (GPS)</b>: to calculate routes, show nearby drivers and track your ride in real time.',
        background:
          '<b>Background location (drivers only)</b>: required to receive ride requests and to enable tracking during ongoing deliveries. Enabled only when a ride is accepted and can be disabled at any time.',
        technical:
          '<b>Technical identifiers</b>: device identifier, push notification token (Firebase Cloud Messaging), OS version, device model.',
        diagnostics:
          '<b>Diagnostic logs</b>: anonymized crash and performance reports (Firebase Crashlytics / Performance) to improve stability.',
        usage:
          '<b>Usage data</b>: actions performed in the app, screens visited (anonymized analytics).',
      },
      generatedTitle: '2.3 Data generated by your use of the Services',
      generated: {
        history:
          '<b>Ride and order history</b>: trips, amounts, ratings, reviews.',
        comms:
          '<b>Communications</b>: messages exchanged via the built-in messaging.',
        voip: '<b>VoIP calls</b>: audio routed in real time via WebRTC between the customer and the driver, with phone numbers masked. <b>The audio content is neither recorded nor stored</b>. Only metadata (date, duration, participants) is kept.',
        proof:
          '<b>Proof-of-delivery photos</b> (parcels and meals) taken by the driver at delivery.',
      },
    },
    s3: {
      title: '3. Purposes and legal bases (GDPR)',
      colPurpose: 'Purpose',
      colBasis: 'Legal basis',
      purposes: {
        account: 'Account creation and management',
        matching: 'Matching drivers and customers, route calculation',
        payment: 'Payment and invoicing',
        verification: 'Driver verification (documents)',
        rideNotifications: 'Ride notifications',
        marketing: 'Marketing notifications',
        security: 'Security, fraud prevention',
        improvement: 'App improvement (analytics, crash logs)',
        judicial: 'Response to judicial requests',
      },
      bases: {
        contract: 'Performance of a contract',
        contractLegal: 'Performance of a contract / Legal obligation',
        legalTransport: 'Legal obligation (passenger transport)',
        consent: 'Consent (revocable)',
        legitimate: 'Legitimate interest',
        legal: 'Legal obligation',
      },
    },
    s4: {
      title: '4. Data sharing',
      intro:
        'We never sell your data. We share it only in the following cases:',
      counterpart:
        '<b>With the driver or the customer</b> of your ride: first name, photo, real-time location, average rating. The real phone number is masked (relayed via VoIP).',
      processors:
        '<b>With our technical processors</b> (data processors under Article 28 GDPR):',
      firebase:
        '<b>Google Firebase</b> (Authentication, Firestore, Cloud Functions, Cloud Messaging, Crashlytics) — Google Ireland Ltd.',
      maps: '<b>Google Maps Platform</b> — routes and mapping.',
      stripe: '<b>Stripe Payments Europe</b> — payment processing.',
      twilio:
        '<b>Twilio / VoIP provider</b> — anonymized calls (to be adapted to your actual provider).',
      authorities:
        '<b>With authorities</b> in the event of a judicial request or legal obligation.',
      transfer:
        '<b>In the event of a business transfer</b>: any acquirer would be subject to the same obligations.',
    },
    s5: {
      title: '5. Transfers outside the EU',
      text: 'Some processors (Google, Stripe) may host data in the United States. These transfers are governed by the <b>European Commission Standard Contractual Clauses</b> and the <b>Data Privacy Framework</b> (EU Commission — adequacy decision of July 10, 2023).',
    },
    s6: {
      title: '6. Retention period',
      active: '<b>Active account</b>: for as long as you use the Services.',
      inactive:
        '<b>Inactive account</b>: 3 years after the last login, then automatic deletion.',
      history:
        '<b>Ride history and invoices</b>: 10 years (accounting obligation).',
      location:
        '<b>Detailed location data</b>: 12 months maximum, then anonymized aggregation.',
      voip: '<b>VoIP call metadata</b>: 12 months.',
      security: '<b>Security logs</b>: 12 months.',
      documents:
        '<b>Verified driver documents</b>: duration of the contract + 5 years.',
    },
    s7: {
      title: '7. Your rights (GDPR)',
      intro: 'You have the following rights at any time:',
      access: '<b>Right of access</b> to your data.',
      rectification: '<b>Right to rectification</b> of inaccurate data.',
      erasure: '<b>Right to erasure</b> ("right to be forgotten").',
      restriction: '<b>Right to restriction</b> of processing.',
      portability:
        '<b>Right to data portability</b> in a structured format.',
      objection:
        '<b>Right to object</b> to processing based on legitimate interest.',
      withdraw: '<b>Right to withdraw your consent</b> at any time.',
      postMortem:
        '<b>Right to set post-mortem directives</b> regarding your data.',
      exerciseBefore: 'To exercise these rights, write to us at',
      exerciseAfter:
        'with proof of identity. We respond within 30 days at most.',
      deleteBefore:
        'You can also delete your account directly from the app: <i>Profile → Settings → Delete my account</i>, or online at',
      complaintBefore:
        'If you believe your rights are not being respected, you may lodge a complaint with the <b>CNIL</b> (the French data protection authority):',
    },
    s8: {
      title: '8. Data security',
      tls: 'TLS 1.2+ encryption for all communications.',
      storage:
        'Data stored on Google Cloud (Firebase), certified ISO 27001, ISO 27017, ISO 27018, SOC 2.',
      mfa: 'Multi-factor authentication available (phone, email).',
      access:
        'Access to data limited to authorized personnel, with logging.',
      payments: 'Payments processed by Stripe (PCI-DSS Level 1).',
    },
    s9: {
      title: '9. Android and iOS permissions',
      location: '<b>Location</b>: find drivers, track the ride.',
      background:
        '<b>Background location</b>: drivers only, during an active ride.',
      microphone:
        '<b>Microphone</b>: VoIP calls with your counterpart (never recorded).',
      camera:
        '<b>Camera and photos</b>: profile photo, document scanning, proof of delivery.',
      notifications:
        '<b>Notifications</b>: ride alerts, messages, payments.',
      bluetooth:
        '<b>Bluetooth</b>: connection to a hands-free kit for calls.',
      revoke:
        'You can revoke each permission at any time from your device settings.',
    },
    s10: {
      title: '10. Minors',
      text: 'The Services are not intended for persons under <b>18 years of age</b>. We do not knowingly collect data from minors. If you discover that a minor has created an account, contact us: we will delete it.',
    },
    s11: {
      title: '11. Cookies and trackers (website)',
      text: 'The website uses only strictly necessary cookies (session, security, preferences). Analytics cookies are placed only after your explicit consent via the banner provided for that purpose.',
    },
    s12: {
      title: '12. Changes to this policy',
      text: 'We may update this policy to reflect legal or technical changes. The date of the last update appears at the top of this page. In the event of a substantial change, we will notify you via the app or by email at least 30 days before it takes effect.',
    },
    s13: {
      title: '13. Contact',
      intro: 'For any question about your data:',
      personal: '📧 Personal data:',
      support: '📧 General support:',
      site: '🌐 Website:',
    },
  },
  terms: {
    metaTitle: 'Terms of Use — Medjira',
    metaDescription:
      'Terms of Use of the Medjira app (taxi, food and parcel delivery).',
    title: 'Terms of Use',
    lastUpdated: 'Last updated: {date}',
    updatedDate: 'May 6, 2026',
    s1: {
      title: '1. Purpose',
      text: 'These Terms of Use ("Terms") govern access to and use of the Medjira mobile application and website (the "Services") published by <b>{company}</b>. By creating an account or using the Services, you accept these Terms without reservation.',
    },
    s2: {
      title: '2. Publisher',
      siteLabel: 'Website:',
      contactLabel: 'Contact:',
    },
    s3: {
      title: '3. Nature of the service',
      text1:
        'Medjira is a <b>matching platform</b> between users (customers) and independent service providers (private-hire/taxi drivers, couriers, restaurateurs). Medjira <b>is not a carrier</b>, nor a restaurateur, and does not itself perform rides, deliveries or food services.',
      text2:
        'Service providers are solely responsible for performing their services, for complying with applicable regulations (transport, hygiene, insurance), and for their own tax and social security status.',
    },
    s4: {
      title: '4. Registration and account',
      age: 'Registration is reserved for adults (18 years of age or older) with legal capacity.',
      accuracy:
        'You warrant the accuracy of the information provided and undertake to keep it up to date.',
      credentials:
        'You are responsible for the confidentiality of your login credentials. Any action performed from your account is deemed to have been performed by you.',
      drivers:
        'Drivers must provide valid documents (licence, insurance, professional card where applicable) and agree to their verification.',
    },
    s5: {
      title: '5. Pricing, payment, cancellation',
      pricingTitle: '5.1 Prices',
      pricing:
        'The price of each ride or delivery is calculated before confirmation, based on distance, estimated duration, type of service and any price surcharge (peak hours, events). The price shown before confirmation is firm, unless you change the route.',
      paymentTitle: '5.2 Payment',
      payment:
        'Online payments are processed exclusively by <b>Stripe Payments Europe</b> (PCI-DSS Level 1 standard). Medjira never stores card numbers. Cash payment to the driver is possible when offered.',
      cancellationTitle: '5.3 Cancellation',
      cancelFree:
        'Free cancellation within a defined period after booking and before the driver arrives.',
      cancelFee:
        'After that, cancellation fees may apply (amount shown in the app).',
      noShow:
        'In the event of a no-show (customer absent after the driver has arrived), a flat fee may be charged.',
      refundTitle: '5.4 Refunds',
      refundBefore:
        'Refund requests (ride not performed, incorrect billing) must be sent to',
      refundAfter:
        'within 14 days. Eligible refunds are credited to the original payment method within 5 to 10 business days.',
    },
    s6: {
      title: '6. User obligations',
      intro: 'You agree to:',
      o1: 'use the Services in accordance with their purpose and applicable regulations;',
      o2: 'not disrupt the operation of the Services (intrusion, security circumvention, scraping, bots);',
      o3: 'not use the Services for unlawful or fraudulent purposes or to harm others;',
      o4: 'respect drivers, couriers and other users; any violent, harassing or discriminatory behavior may result in account suspension;',
      o5: 'not transport illegal or dangerous goods, or goods contrary to insurance conditions.',
    },
    s7: {
      title: '7. Liability',
      intro:
        'Medjira acts as a <b>technical intermediary</b> and cannot be held liable for:',
      l1: 'damage caused during the performance of services by independent providers (covered by their own insurance);',
      l2: 'temporary unavailability of the Services (maintenance, third-party incidents, force majeure);',
      l3: 'payment incidents resulting from a malfunction of Stripe or your bank.',
      limit:
        "Medjira's liability, where incurred, is limited to the amount of the ride or delivery concerned.",
    },
    s8: {
      title: '8. Personal data',
      before: 'The processing of your data is described in our',
      privacyLink: 'Privacy Policy',
      middle:
        '. You may delete your account at any time from the app (Profile → Delete my account) or via the public page',
    },
    s9: {
      title: '9. Intellectual property',
      text: 'The Medjira name, logo, graphic elements, interface, texts and source code are the exclusive property of {company}. Any unauthorized reproduction, representation or exploitation is prohibited.',
    },
    s10: {
      title: '10. Suspension and termination',
      text: 'Medjira may suspend or terminate an account in the event of a serious breach of these Terms, proven fraud, or behavior endangering the safety of other users. Suspension is notified by email. You may close your account at any time from the app.',
    },
    s11: {
      title: '11. Changes to the Terms',
      text: 'Medjira may amend the Terms to reflect legal, technical or commercial changes. Substantial changes will be notified to you at least 30 days before they take effect. Continued use of the Services constitutes acceptance of the new Terms.',
    },
    s12: {
      title: '12. Governing law and jurisdiction',
      before:
        'These Terms are governed by <b>French law</b>. Failing an amicable resolution, any dispute will be brought before the competent French courts, in accordance with the rules of ordinary law. Consumers may use the <b>European online dispute resolution platform</b> free of charge:',
    },
    s13: {
      title: '13. Contact',
      support: '📧 Support:',
      legal: '⚖️ Legal questions:',
    },
  },
  deleteAccount: {
    metaTitle: 'Delete my account — Medjira',
    metaDescription:
      'Medjira account deletion request. GDPR-compliant procedure meeting Google Play requirements.',
    title: 'Delete my Medjira account',
    application: 'App: <b>{app}</b> — Publisher: {company}',
    privacyLink: 'Privacy policy',
    termsLink: 'Terms of use',
    inApp: {
      title: '✅ Recommended method — directly in the app',
      intro:
        'If you still have access to your account, deletion is <b>immediate</b> from the Medjira app:',
      step1: 'Open the Medjira app',
      step2: 'Go to the <b>Profile</b> tab',
      step3: 'Scroll down to <b>“Delete my account”</b> at the bottom of the screen',
      step4: 'Confirm your choice in the dialog that appears',
      irreversible: 'Deletion is permanent and cannot be undone.',
    },
    noAccess: {
      title: 'Can no longer access your account?',
      intro:
        'Use the form below to request deletion by email. Our team will process your request within <b>30 days at most</b> (GDPR Article 12), usually within 7 business days.',
      indicate: 'To process your request, please provide:',
      item1: 'the email address of the account;',
      item2: 'the associated phone number (in international format, e.g. +33...);',
      item3: 'the account type (customer, driver, restaurant owner).',
      verification:
        'You may be asked to verify your identity to prevent fraudulent deletions.',
      sendButton: '✉️ Send my request to {email}',
      fallback: 'If the button does not work, write directly to',
    },
    deleted: {
      title: 'What data is deleted?',
      intro: 'Deletion permanently erases:',
      profile: 'your profile (last name, first name, email, phone, photo);',
      auth: 'your Firebase authentication credentials;',
      addresses: 'your saved addresses and preferences;',
      payment:
        'your saved payment methods (Stripe cards are detached by our payment provider);',
      messages: 'your in-app chat messages;',
      push: 'your push notification tokens (FCM).',
    },
    kept: {
      title: 'What data is kept?',
      intro: 'Some data must legally be kept after your account is deleted:',
      invoices:
        '<b>Invoices and ride history</b>: kept for <b>10 years</b> (accounting obligation — art. L.123-22 French Commercial Code), in a form dissociated from your identity.',
      voip: '<b>VoIP call metadata</b> (date, duration — not the content): <b>12 months</b>.',
      security: '<b>Security logs</b>: <b>12 months</b>.',
      documents: '<b>Verified drivers’ regulatory documents</b>: contract duration + 5 years.',
      more: 'More details in our',
    },
    timing: {
      title: 'Processing time',
      inApp: '<b>In-app deletion</b>: immediate.',
      email: '<b>Email request</b>: within 30 days at most, usually within 7 business days.',
      confirmation: 'You will receive a confirmation email once the deletion is complete.',
    },
    contact: {
      title: 'A question?',
      privacy: '📧 Personal data:',
      support: '📧 General support:',
      complaint:
        'If you believe your rights are not being respected, you can lodge a complaint with the <b>CNIL</b>:',
    },
    mailSubject: 'Medjira account deletion request',
    mailBody:
      'Hello,\n\nI am requesting the permanent deletion of my Medjira account and all associated personal data, in accordance with Article 17 of the GDPR.\n\nAccount identifiers (to be completed):\n- Account email address: \n- Associated phone number: \n- Account type (customer / driver / restaurant owner): \n\nI certify that I am the holder of the account concerned.\n\nKind regards,',
    enSummary: {
      title: '🌐 English Summary — How to delete your account',
      intro:
        'In compliance with Google Play and Apple guidelines, you can delete your account and personal data at any time:',
      step1: 'Open the <b>Medjira</b> app',
      step2: 'Go to the <b>Profile</b> tab',
      step3: 'Scroll down to <b>“Delete my account”</b>',
      step4: 'Confirm your choice in the dialog prompt',
      noAccess: 'If you can no longer log in, send your deletion request to',
      noAccessDetails:
        'including your registered email, phone number, and user role. Requests are processed within 30 days maximum.',
    },
  },
} as const;
