'use client';

import { cn } from '@/lib/utils';
import {
  ArrowDown,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowDownUp,
  ArrowUp,
  ArrowUpRight,
  BadgeCheck,
  Ban,
  BellOff,
  Bell,
  Bike,
  BookOpen,
  Brain,
  BriefcaseBusiness,
  Camera,
  CarFront,
  CarTaxiFront,
  Calendar,
  CalendarCheck,
  CalendarDays,
  ChartNoAxesColumnIncreasing,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleAlert,
  CircleCheck,
  CircleHelp,
  CircleX,
  ClipboardCheck,
  ClipboardList,
  Clock3,
  DoorOpen,
  CreditCard,
  Download,
  ExternalLink,
  History,
  Headphones,
  Hourglass,
  Flower2,
  FileText,
  FolderOpen,
  Heart,
  HelpCircle,
  Home,
  Info,
  KeyRound,
  LayoutGrid,
  List,
  ListFilter,
  LayoutDashboard,
  LocateFixed,
  LockKeyhole,
  LogIn,
  LogOut,
  Mail,
  MailCheck,
  MapPin,
  MessageCircle,
  Mic,
  MicOff,
  Minus,
  Navigation,
  NotebookPen,
  Package,
  Paperclip,
  Pencil,
  Phone,
  PhoneCall,
  PhoneOff,
  Play,
  Plus,
  Power,
  Receipt,
  ReceiptText,
  RefreshCw,
  RotateCcw,
  Rocket,
  Route,
  Search,
  SearchX,
  ScanEye,
  Send,
  Settings,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Star,
  Stethoscope,
  Store,
  StickyNote,
  Timer,
  Trash2,
  TriangleAlert,
  Truck,
  Utensils,
  Upload,
  UserPlus,
  UserRound,
  UserRoundX,
  UsersRound,
  Wallet,
  WalletCards,
  Volume2,
  VolumeX,
  TrendingUp,
  Zap,
  Box,
  X,
  type LucideIcon,
} from 'lucide-react';

interface MaterialIconProps {
  readonly name: string;
  readonly className?: string;
  readonly filled?: boolean;
  readonly size?: 'sm' | 'md' | 'lg' | 'xl';
}

const sizeMap = {
  sm: 'text-[16px]',
  md: 'text-[20px]',
  lg: 'text-[24px]',
  xl: 'text-[32px]',
} as const;

export const materialIconMap: Record<string, LucideIcon> = {
  address: MapPin,
  add: Plus,
  add_card: CreditCard,
  admin_panel_settings: ShieldCheck,
  arrow_back: ArrowLeft,
  arrow_downward: ArrowDown,
  arrow_forward: ArrowRight,
  arrow_outward: ArrowUpRight,
  arrow_upward: ArrowUp,
  assignment: ClipboardList,
  attach_file: Paperclip,
  bar_chart: ChartNoAxesColumnIncreasing,
  block: Ban,
  bolt: Zap,
  call: PhoneCall,
  call_end: PhoneOff,
  cancel: CircleX,
  check: Check,
  check_circle: CircleCheck,
  calendar_month: CalendarDays,
  calendar_today: Calendar,
  chat: MessageCircle,
  chevron_down: ChevronDown,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  chevron_up: ChevronUp,
  circle: Circle,
  compare_arrows: ArrowLeftRight,
  credit_card: CreditCard,
  dashboard: LayoutDashboard,
  delete: Trash2,
  delivery_dining: Bike,
  delete_forever: Trash2,
  description: FileText,
  directions: Navigation,
  directions_bike: Bike,
  directions_car: CarFront,
  download: Download,
  done_all: CheckCheck,
  door_front: DoorOpen,
  drive_eta: CarFront,
  edit: Pencil,
  edit_note: Pencil,
  error: CircleAlert,
  error_outline: CircleAlert,
  event: Clock3,
  event_available: CalendarCheck,
  expand_more: ChevronDown,
  fact_check: ClipboardCheck,
  favorite: Heart,
  filter_list: ListFilter,
  folder_open: FolderOpen,
  grid_view: LayoutGrid,
  group: UsersRound,
  history: History,
  help_outline: HelpCircle,
  home: Home,
  hourglass_empty: Hourglass,
  hourglass_top: Hourglass,
  info: Info,
  inventory_2: Package,
  key: KeyRound,
  list_alt: List,
  local_taxi: CarTaxiFront,
  local_florist: Flower2,
  local_shipping: Truck,
  location_on: MapPin,
  lunch_dining: Utensils,
  lock: LockKeyhole,
  login: LogIn,
  logout: LogOut,
  mail: Mail,
  mark_email_read: MailCheck,
  medical_services: Stethoscope,
  map: MapPin,
  mic: Mic,
  mic_off: MicOff,
  menu_book: BookOpen,
  message: MessageCircle,
  my_location: LocateFixed,
  navigation: Navigation,
  note: StickyNote,
  notes: NotebookPen,
  notifications: Bell,
  notifications_off: BellOff,
  open_in_new: ExternalLink,
  package_2: Box,
  payments: CreditCard,
  people: UsersRound,
  person: UserRound,
  person_add: UserPlus,
  person_off: UserRoundX,
  person_pin: MapPin,
  person_remove: UserRoundX,
  photo_camera: Camera,
  phone: Phone,
  pin: MapPin,
  play_arrow: Play,
  power_settings_new: Power,
  progress_activity: RefreshCw,
  psychology: Brain,
  receipt: Receipt,
  receipt_long: ReceiptText,
  refresh: RefreshCw,
  replay: RotateCcw,
  remove: Minus,
  restaurant: Utensils,
  rocket_launch: Rocket,
  route: Route,
  schedule: Clock3,
  search: Search,
  search_off: SearchX,
  send: Send,
  settings: Settings,
  shopping_bag: ShoppingBag,
  shopping_cart: ShoppingCart,
  star: Star,
  store: Store,
  storefront: Store,
  support_agent: Headphones,
  swap_horiz: ArrowLeftRight,
  swap_vert: ArrowDownUp,
  sync_alt: ArrowLeftRight,
  timer: Timer,
  today: CalendarDays,
  trending_up: TrendingUp,
  upload_file: Upload,
  verified: BadgeCheck,
  verified_user: BadgeCheck,
  viewport: ScanEye,
  volume_off: VolumeX,
  volume_up: Volume2,
  warning: TriangleAlert,
  wallet: Wallet,
  account_balance_wallet: WalletCards,
  weekend: CalendarDays,
  where_to_vote: LocateFixed,
  wifi: Circle,
  wifi_off: CircleX,
  work: BriefcaseBusiness,
  close: X,
};

export function MaterialIcon({ name, className, filled = false, size = 'lg' }: MaterialIconProps) {
  const Icon = materialIconMap[name] ?? CircleHelp;

  return (
    <Icon
      aria-hidden="true"
      className={cn('inline-flex items-center justify-center leading-none shrink-0 align-middle size-[1em]', sizeMap[size], className)}
      fill={filled ? 'currentColor' : 'none'}
      strokeWidth={filled ? 1.75 : 2}
    />
  );
}
