'use client';

import { cn } from '@/lib/utils';
import {
  ArrowDown,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowUp,
  BadgeCheck,
  Ban,
  Bell,
  Bike,
  BookOpen,
  Camera,
  CarFront,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleAlert,
  CircleCheck,
  CircleHelp,
  CircleX,
  ClipboardCheck,
  ClipboardList,
  Clock3,
  CreditCard,
  Download,
  History,
  Hourglass,
  Info,
  KeyRound,
  LayoutDashboard,
  LocateFixed,
  LockKeyhole,
  LogIn,
  LogOut,
  Mail,
  MapPin,
  MessageCircle,
  Minus,
  Navigation,
  NotebookPen,
  Paperclip,
  Pencil,
  Phone,
  PhoneCall,
  PhoneOff,
  Play,
  Plus,
  Power,
  ReceiptText,
  RefreshCw,
  Rocket,
  Route,
  Search,
  SearchX,
  Send,
  ShieldCheck,
  ShoppingBag,
  Star,
  Store,
  Trash2,
  TriangleAlert,
  Utensils,
  UserPlus,
  UserRound,
  UserRoundX,
  Wallet,
  WalletCards,
  X,
  type LucideIcon,
} from 'lucide-react';

interface MaterialIconProps {
  readonly name: string;
  readonly className?: string;
  readonly filled?: boolean;
  readonly size?: 'sm' | 'md' | 'lg' | 'xl';
}

const sizeMap = {
  sm: 'text-[16px]',
  md: 'text-[20px]',
  lg: 'text-[24px]',
  xl: 'text-[32px]',
} as const;

const iconMap: Record<string, LucideIcon> = {
  add: Plus,
  add_card: CreditCard,
  admin_panel_settings: ShieldCheck,
  arrow_back: ArrowLeft,
  arrow_downward: ArrowDown,
  arrow_forward: ArrowRight,
  arrow_upward: ArrowUp,
  assignment: ClipboardList,
  attach_file: Paperclip,
  block: Ban,
  call: PhoneCall,
  call_end: PhoneOff,
  cancel: CircleX,
  check: Check,
  check_circle: CircleCheck,
  chevron_down: ChevronDown,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  chevron_up: ChevronUp,
  circle: Circle,
  credit_card: CreditCard,
  dashboard: LayoutDashboard,
  delivery_dining: Bike,
  delete_forever: Trash2,
  directions_car: CarFront,
  download: Download,
  edit: Pencil,
  edit_note: Pencil,
  error: CircleAlert,
  error_outline: CircleAlert,
  event: Clock3,
  expand_more: ChevronDown,
  fact_check: ClipboardCheck,
  history: History,
  hourglass_empty: Hourglass,
  hourglass_top: Hourglass,
  info: Info,
  key: KeyRound,
  local_taxi: CarFront,
  location_on: MapPin,
  lock: LockKeyhole,
  login: LogIn,
  logout: LogOut,
  mail: Mail,
  map: MapPin,
  menu_book: BookOpen,
  message: MessageCircle,
  my_location: LocateFixed,
  navigation: Navigation,
  notes: NotebookPen,
  notifications: Bell,
  payments: CreditCard,
  person: UserRound,
  person_add: UserPlus,
  person_off: UserRoundX,
  person_remove: UserRoundX,
  phone: Phone,
  pin: MapPin,
  play_arrow: Play,
  power_settings_new: Power,
  progress_activity: RefreshCw,
  receipt_long: ReceiptText,
  refresh: RefreshCw,
  remove: Minus,
  restaurant: Utensils,
  rocket_launch: Rocket,
  route: Route,
  schedule: Clock3,
  search: Search,
  search_off: SearchX,
  send: Send,
  shopping_bag: ShoppingBag,
  star: Star,
  store: Store,
  storefront: Store,
  swap_horiz: ArrowLeftRight,
  verified: BadgeCheck,
  verified_user: BadgeCheck,
  warning: TriangleAlert,
  wallet: Wallet,
  account_balance_wallet: WalletCards,
  where_to_vote: LocateFixed,
  wifi: Circle,
  wifi_off: CircleX,
  close: X,
};

export function MaterialIcon({ name, className, filled = false, size = 'lg' }: MaterialIconProps) {
  const Icon = iconMap[name] ?? CircleHelp;

  return (
    <Icon
      aria-hidden="true"
      className={cn('inline-flex items-center justify-center leading-none shrink-0 align-middle size-[1em]', sizeMap[size], className)}
      fill={filled ? 'currentColor' : 'none'}
      strokeWidth={filled ? 1.75 : 2}
    />
  );
}
